services:
  dt4h-modelannotation-api:
    container_name: dt4h-modelannotation-api
    build: .
    user: root
    environment:
      DICTIONARY_FILE:
      LANGUAGE: en
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: unless-stopped
    privileged: true
    command: flask run --host=0.0.0.0 --port=8000

networks:
  default:
    name: cogstack-net
    external: true
